# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  dtslint:
    name: dtslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: NVMRC=$(cat .nvmrc)

      - uses: actions/setup-node@v1
        with:
          node-version: ${NVMRC}
      - run: npm ci
      - run: npm run dtslint

  tslint:
    name: TSLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: NVMRC=$(cat .nvmrc)

      - uses: actions/setup-node@v1
        with:
          node-version: ${NVMRC}
      - run: npm ci
      - run: npm run tslint

  type-check:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: NVMRC=$(cat .nvmrc)

      - uses: actions/setup-node@v1
        with:
          node-version: ${NVMRC}
      - run: npm ci
      - run: npm run type-check

  publish-npm:
    name: Publish to NPM
    needs: [dtslint,tslint,type-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: NVMRC=$(cat .nvmrc)

      - uses: actions/setup-node@v1
        with:
          node-version: ${NVMRC}
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
