# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PR checks

on:
  pull_request:
    branches: [ master ]

jobs:
  tslint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read .nvmrc
      run: NVMRC=$(cat .nvmrc)

    - name: Echo .NVMRC
      run: echo "use node.js ${NVMRC}"

    - name: Use Node.js ${NVMRC}
      uses: actions/setup-node@v1
      with:
        node-version: ${NVMRC}
    - run: npm ci
    - run: npm run tslint

  dtslint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read .nvmrc
      run: NVMRC=$(cat .nvmrc)

    - name: Use Node.js ${NVMRC}
      uses: actions/setup-node@v1
      with:
        node-version: ${NVMRC}
    - run: npm ci
    - run: npm run dtslint
    
  type-check:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read .nvmrc
      run: NVMRC=$(cat .nvmrc)

    - name: Use Node.js ${NVMRC}
      uses: actions/setup-node@v1
      with:
        node-version: ${NVMRC}
    - run: npm ci
    - run: npm run type-check
